spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#开启feign支持hystrix  (注意，一定要开启，旧版本默认支持，新版本默认关闭)
# #修改调用超时时间（默认是1秒就算超时）
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
  